# Borrowed from https://github.com/sfackler/rust-postgres/blob/04bd98e7edb238511661b311c725a176012bca6a/.circleci/config.yml
# Used under MIT license.

restore_registry: &RESTORE_REGISTRY
  restore_cache:
    key: registry
save_registry: &SAVE_REGISTRY
  save_cache:
    key: registry-{{ .BuildNum }}
    paths:
    - /usr/local/cargo/registry/index

version: 2.1
jobs:
  buildtest:
    docker:
      - image: cimg/rust:1.75
        environment:
          RUSTFLAGS: -D warnings
          MERGE_BASE: main
    steps:
      - checkout
      - run: |
              upstream=${CIRCLE_REPOSITORY_URL:-$(git remote  get-url origin)}
              git config --global user.email "circleci@invalid.example"
              git config --global user.name "CircleCI build for ${upstream}"
              echo "Merging with: ${MERGE_BASE}"
              git merge --no-edit --no-ff "origin/${MERGE_BASE}"
      - run: rustup component add rustfmt
      - run: rustfmt --version
      - run: cargo fmt -- --check
      - *RESTORE_REGISTRY
      - run: rustc --version | tee ~/rust-version
      - run: cargo build --all --tests --features skip-end-to-end
      - *SAVE_REGISTRY
      - run: cargo test --all --features skip-end-to-end
      - run: sudo ./.circleci/install-rabbitmq.sh
      - run: cargo test --all
workflows:
  testall:
    jobs:
      - buildtest
